name: flutter_value_stream_builder
description: A builder for ValueStreams
version: 0.1.0
author: Kåda Development AB
homepage: https://kada.se

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  rxdart: ^0.27.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
